import { createApp } from "velociradix";
import { registerVelociradixRoutes } from "./src/routes/velociradixRoutes.js";

const app = createApp();

// Register CRUD Routes (Ordered 1 to 7)
registerVelociradixRoutes(app);

// Awesome Postman Collection Options
const postmanCollectionOpts = {
  name: "User Management API (Assignment 3)",
  description: `⚡ User Management API — Assignment 3 Collection

Welcome to the Official Postman API Collection for Assignment 3 (User Management System), automatically generated by Velociradix — the ultra-fast C++ powered Node.js web engine.

🚀 Key Features:
• Persistent JSON Storage: All user records are saved to data/users.json using fs/promises.
• Unique Email Validation: Enforces unique email check on user registration & updates.
• Complete CRUD Standard: Includes all 7 endpoints with 200, 201, 400, and 404 response examples.
• Ultra-Fast Latency: Powered by Velociradix native C++ event engine (< 1ms execution time).

📋 Endpoints Summary:
1. POST /user — Add a new user with unique email validation.
2. PATCH /user/:id — Update existing user details (name, age, email) by ID.
3. DELETE /user/:id & DELETE /user — Remove a user by ID via URL params or JSON body.
4. GET /user/getByName?name=... — Retrieve a user by name via query parameter.
5. GET /user — Retrieve all users from storage.
6. GET /user/filter?minAge=... — Filter users by minimum age requirement.
7. GET /user/:id — Retrieve a single user by unique ID parameter.`,
};

// Register documentation endpoints AFTER all application routes
app.postmanDoc("/postman-docs", postmanCollectionOpts);

app.get(
  "/postman.json",
  (ctx) => {
    return ctx.status(200).json(app.postman(postmanCollectionOpts));
  },
  {
    name: "Export Postman Collection JSON",
    description:
      "Get the full Postman collection JSON file to import into Postman desktop or web.",
  },
);

const PORT = 3000;
app.listen(PORT, () => {
  console.log(`Velociradix server is running on http://localhost:${PORT}`);
  console.log(
    `Interactive Postman Documentation UI: http://localhost:${PORT}/postman-docs`,
  );
  console.log(
    `Downloadable Postman Collection JSON: http://localhost:${PORT}/postman.json`,
  );
});
